import "~/styles/globals.css";

import { type Metadata } from "next";
import Providers from "./providers";
import NextTopLoader from 'nextjs-toploader';
import { DM_Sans, Space_Grotesk } from 'next/font/google';
import Navbar from "~/components/Navbar";

export const metadata: Metadata = {
  title: "ChatPDF Reader",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const sans = DM_Sans({
  subsets: ['latin'],
  weight: ['500','800']
})

const grotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
  <html lang="en" className={grotesk.className}>
      <body>
        <Providers>
          <Navbar />
         <NextTopLoader height={4} color="#22c55e" showSpinner={false}/>
         {children}
         </Providers>
      </body>
    </html>
  );
}
