import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster} from 'sonner'
import Providers from "./providers";
import LogoutButton from "~/components/LogoutButton";
import NextTopLoader from 'nextjs-toploader';
import { Lexend } from 'next/font/google';


export const metadata: Metadata = {
  title: "ChatPDF Reader",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '700'], // adjust weights as needed
});


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={lexend.className}>
      <body>
        <Providers>
         <LogoutButton />
         <Toaster position="top-center" richColors/>
         <NextTopLoader height={4} color="#9b1136" showSpinner={false}/>
         {children}
         </Providers>
      </body>
    </html>
  );
}
